on: [push]

jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - uses: SkySoft-ATM/download-asset-action@master
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          owner: "SkySoft-ATM"
          repo: "gRPC-VC2015"
          tag: "V1.0"
          asset-name: "grpc-visual2015.zip"
          dir: "./"          
